spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    type: org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory.EmbeddedDataSourceProxy
#    url: jdbc:h2:mem:db
    url: jdbc:sqlserver://localhost:1433;databaseName=hazelcast
    username: sa
    password: sa
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
#    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    database: sql_server
  config:
    activate:
      on-profile:

